version: '3.9'

services:
  mongodb:
    image: mongo:7
    container_name: iot-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: iot_dashboard
    networks:
      - iot-net

  backend:
    build: ./backend
    container_name: iot-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/iot_dashboard
      NODE_ENV: production
    networks:
      - iot-net

  frontend:
    build: ./frontend
    container_name: iot-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://backend:5000
      VITE_SOCKET_URL: http://backend:5000
    networks:
      - iot-net

  sensor:
    build: ./sensor-simulator
    container_name: iot-simulator
    restart: always
    depends_on:
      - backend
    environment:
      SOCKET_SERVER: http://backend:5000
    networks:
      - iot-net

volumes:
  mongo_data:

networks:
  iot-net:
    driver: bridge
